### ISSUE TITLE
UTGR02 - Ac Yr and Grad Date don't align

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utValidateR#93] opened 2023-01-24 23:22 UTC
Need to add graduation date to the display.

**Comment by cdemkegit** [comment] 2024-11-07 17:57
@mkhassan-isu This is one of the issues I hope may be resolved in the [DataStewardsAudits ](https://github.com/ut-effectiveness/DataStewardAudits) 

Steps to take:
1. We can check to see if the data point is in the sql and/or pin 
2. We need to determine  if this is something we can change in the App or do we need to change something in the utValidateR package as well. 
3. We can see what it takes to add a data point to the correct data table, this should be in the R/load_data.R file.
4. We need to see what it takes to add that new field on the dyplay tables in the Golem App itself, not sure what file that is.

**Comment by mkhassan-isu** [comment] 2024-11-12 19:48
The issue is fixed in DataStewardsAudits.

**Closed by mkhassan-isu** 2024-11-12 19:48 UTC
Labels: bug, enhancement
