### ISSUE TITLE
S42a - Data a data field for reference

### ISSUE THREAD

**Issue by andreabringhurst** [ut-effectiveness/utValidateR#89] opened 2023-01-23 20:36 UTC
Please add student type as a reference.  This will help admissions determine if the student "should" have a high school code.

**Comment by cdemkegit** [comment] 2024-11-07 18:00
@mkhassan-isu This is one of the issues I hope may be resolved in the [DataStewardsAudits ](https://github.com/ut-effectiveness/DataStewardAudits) 

Steps to take:
1. We can check to see if the data point is in the sql and/or pin 
2. We need to determine  if this is something we can change in the App or do we need to change something in the utValidateR package as well. 
3. We can see what it takes to add a data point to the correct data table, this should be in the R/load_data.R file.
4. We need to see what it takes to add that new field on the display tables in the Golem App itself, not sure what file that is.

**Comment by andreabringhurst** [comment] 2024-11-09 03:42
I agree, they should be able to be addressed in the DataStewardsAudits since I'm requesting changes to the data displayed, not the data being checked.

**Comment by mkhassan-isu** [comment] 2024-11-12 19:47
The issue is fixed in DataStewardsAudits.

**Closed by mkhassan-isu** 2024-11-12 19:47 UTC
Labels: bug, enhancement
